version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    hostname: nginx
    container_name: nginx
    links:
      - php-fpm
    volumes_from:
      - php-fpm
  php-fpm:
    build: ./php-fpm
    hostname: php-fpm
    container_name: php-fpm
    volumes:
      - /var/www
